#!/bin/bash
# ========================================
# Author: Abhishek Oli Kshetri
# Course: COMP2137 - Linux Administration
# Purpose: Generate a detailed system information report
# ========================================
# -----------------------------
# Collect system information
# -----------------------------
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)
OS=$(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"')
UPTIME=$(uptime -p)
CPU=$(lshw -class processor 2>/dev/null | grep 'product' | head -1 | awk -F': ' '{print $2}')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISK=$(lsblk -d -o NAME,SIZE,MODEL | grep -v NAME)
VIDEO=$(lshw -class display 2>/dev/null | grep 'product' | awk -F': ' '{print $2}' | head -1)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd,)
# -----------------------------
# Collect system status
# -----------------------------
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd, )
DISKSPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd, )
PROCESSCOUNT=$(ps -e --no-headers | wc -l)
LOADAVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
LISTENPORTS=$(ss -tuln 2>/dev/null | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd, )
UFWSTATUS=$(sudo ufw status | head -n 1)
# -----------------------------
# Display the report
# -----------------------------
echo ""
echo "System Report for $HOSTNAME generated by $USERNAME, on $DATE"
echo ""
echo "System Information"
echo "------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s):"
echo "$DISK"
echo "Video: $VIDEO"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISKSPACE"
echo "Process Count: $PROCESSCOUNT"
echo "Load Averages: $LOADAVG"
echo "Listening Network Ports: $LISTENPORTS"
echo "UFW Status: $UFWSTATUS"
echo ""
clear
cd ~/COMP2137
touch system_report.sh
nano system_report.sh
chmod +x system_report.sh
bash system_report.sh

git add system_report.sh
git commit -m "Added system information report script"
git push
cd ~/Downloads
cd ~/COMP2137
cd
sudo apt update
sudo apt install git -y
git config --global user.name "Abhishek Oli Kshetri"
git config --global user.email "abhishekolikshetri@gmail.com" 
cd ~
git init
git add system_report.sh
git commit -m "Added system information report script"
git branch -M main
git remote add origin https://github.com/abhishekolikshetri/COMP2137-SystemReport.git
git push -u origin main
git config --global credential.helper store
ping -c 3 8.8.8.8
ping -c 3 google.com
sudo reboot
ip a
ping -c 3 8.8.8.8
ping -c 3 google.com
[200~ping -c 3 8.8.8.8
~ping -c 3 8.8.8.8
ping -c 3 8.8.8.8
sudo dhclient -r
sudo dhclient
ip a
sudo nano /etc/resolv.conf
sudo apt update
wget -O ~/repositoryname/makecontainers.sh https://github.com/zonzorp/COMP2137/raw/main/makecontainers.sh && chmod +x ~/repositoryname/makecontainers.sh
ls ~
wget -O ~/COMP2137/makecontainers.sh https://github.com/zonzorp/COMP2137/raw/main/makecontainers.sh && chmod +x ~/COMP2137/makecontainers.sh
~/COMP2137/makecontainers.sh --prefix server --count 2 --fresh
sudo reboot
