#!/bin/bash
# Author: Abhishek Oli Kshetri
# Purpose: Generate a detailed system information report

# ===============================
# Collect system information
# ===============================

HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)
OS=$(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"')
UPTIME=$(uptime -p)
CPU=$(lshw -class processor | grep 'product' | head -1 | awk -F': ' '{print $2}')
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISK=$(lsblk -d -o NAME,SIZE,MODEL | grep -v NAME)
VIDEO=$(lshw -class display | grep 'product' | awk -F': ' '{print $2}' | head -1)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd,)

# ===============================
# Collect system status
# ===============================

USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd,)
DISKSPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd, )
PROCESSCOUNT=$(ps -e --no-headers | wc -l)
LOADAVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
LISTENPORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F':' '{print $NF}' | sort -n | uniq | paste -sd, )
UFWSTATUS=$(sudo ufw status | head -n 1)

# ===============================
# Display the report
# ===============================

echo ""
echo "System Report for $HOSTNAME generated by $USERNAME, on $DATE"
echo ""
echo "System Information"
echo "------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s): $DISK"
echo "Video: $VIDEO"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISKSPACE"
echo "Process Count: $PROCESSCOUNT"
echo "Load Averages: $LOADAVG"
echo "Listening Network Ports: $LISTENPORTS"
echo "UFW Status: $UFWSTATUS"
echo ""
